In [7]:
import numpy as np

# NumPy Creating Arrays
arr = np.array([1,2,3,4,5])
print(arr)
print(type(arr))


[1 2 3 4 5]
<class 'numpy.ndarray'>


In [12]:
# Dimensions in Arrays

# 0-D Arrays
arr = np.array(50)
print(arr)
# 1-D Arrays
arr2 = np.array([1,2,3])
print(arr2)
# 2D Array
# These are often used to represent matrix or 2nd order tensors.
# NumPy has a whole sub module dedicated towards matrix operations called numpy.mat

arr3 = np.array([[1,2,3],[4,5,6]])
print(arr3)
# 3-D arrays
arr4 = [[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]]
# print(arr4[1][0][1])

50
[1 2 3]
[[1 2 3]
 [4 5 6]]
8


In [16]:
# Check Number of Dimensions?
# NumPy Arrays provides the ndim attribute that returns an integer that tells us how many dimensions the array have.
a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [22]:
# Higher Dimensional Arrays
# An array can have any number of dimensions.
# When the array is created, you can define the number of dimensions by using the ndmin argument.
arr = np.array([1,2,3],ndmin=5)
print(arr)
print('No of dimensions are',arr.ndim)

[[[[[1 2 3]]]]]
No of dimensions are 5


In [24]:
# New Chapter
# NumPy Array Indexing
# Access Array Elements
# Array indexing is the same as accessing an array element.

# Access 2-D Arrays
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
# 4
print(arr[0][3])
# 9
print(arr[1][3])


4
9


In [27]:
# Access 3-D Arrays
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
# 0 index = [[1, 2, 3], [4, 5, 6]]
# 1 index = [[7, 8, 9], [10, 11, 12]]
# 5
print(arr[0][1][1])
# 8
print(arr[1][0][1])
# 12
print(arr[1][1][2])

5
8
12


In [28]:
# Negative Indexing
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
# 10
print(arr[1][-1])

10


In [35]:
# New Chapter
# NumPy Array Slicing (same as was in list)

# STEP
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[1:-1:2])
# same as
print(arr[1::2]) 
# both print elements with step 2


[2 4 6]
[2 4 6]


In [42]:
# Slicing 2-D Arrays

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
# 7,8,9
print(arr[1,1:4])
# 1,2,3,4
print(arr[0,0:4])
# But if we want to extract same element index from both arrays
print(arr[0:2,0:4])


[7 8 9]
[1 2 3 4]
[[1 2 3 4]
 [6 7 8 9]]


In [2]:
# New Chapter
# Checking the Data Type of an Array
# The NumPy array object has a property called (dtype) that returns the data type of the array:

import numpy as np

arr = np.array([1, 2, 3, 4])
arr2 = np.array(['a','b','c'])
print(arr)
print(arr.dtype) # it is a property, we can access it with dot without parethesis
print(arr2)
print(arr2.dtype)



[1 2 3 4]
int32
['a' 'b' 'c']
<U1


In [6]:
# Converting Data Type on Existing Arrays
# The best way to change the data type of an existing array, is to make a copy of the array with the astype() method.
# astype()

import numpy as np

arr = np.array([1.1, 2.1, 3.1])
newarr = arr.astype('i')
print(newarr)
print(newarr.dtype)

[1 2 3]
int32


In [8]:
# New Chapter
# NumPy Array Copy vs View

# The Difference Between Copy and View
# The main difference between a copy and a view of an array is that the copy is a new array, and the view is just a view of the original array.

'''
The copy owns the data and any changes made to the copy will not affect original array, and any changes made to the original array will not affect the copy.

The view does not own the data and any changes made to the view will affect the original array, and any changes made to the original array will affect the view.
'''
import numpy as np
arr = np.array([1,2,3])
newArr = arr.copy()
newArr[2] = 10
print(arr)
print(newArr)


[1 2 3]
[ 1  2 10]


In [9]:
import numpy as np
arr = np.array([1,2,3])
newArr = arr.view()
newArr[2] = 10
print(arr)
print(newArr)
# The original array SHOULD be affected by the changes made to the view.


[ 1  2 10]
[ 1  2 10]


In [10]:
'''
Check if Array Owns it's Data

As mentioned above, copies owns the data, and views does not own the data, but how can we check this?

Every NumPy array has the attribute base that returns None if the array owns the data.

Otherwise, the base  attribute refers to the original object. 
'''
#base is a property
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

x = arr.copy()
y = arr.view()

print(x.base)
print(y.base) 
# The copy returns None.
# The view returns the original array.

None
[1 2 3 4 5]


In [14]:
# Shape of an Array
# The shape of an array is the number of elements in each dimension.
# shape it is a attribute/property
import numpy as np

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(arr.shape)
# (2,4) means 2 arrays with 4 elements each
arr2 = np.array([[1, 2, 3, 4], [5, 6, 7, 8],[5, 6, 7, 8]])
print(arr2.shape) # (3,4)


(2, 4)
(3, 4)


In [15]:
# Create an array with 5 dimensions using ndmin
import numpy as np

arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('shape of array :', arr.shape) 

[[[[[1 2 3 4]]]]]
shape of array : (1, 1, 1, 1, 4)


In [16]:
# Reshaping arrays
'''
Reshaping means changing the shape of an array.
By reshaping we can add or remove dimensions or change number of elements in each dimension.
'''
# Reshape From 1-D to 2-D
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(4, 3) # 4 Rows, 3 Columns

print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [17]:
# Reshape From 1-D to 3-D
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(2, 3, 2) # 2 2D arrays, with 3 rows and 2 columns

print(newarr) 

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [ ]:
# Can We Reshape Into any Shape?

# Yes, as long as the elements required for reshaping are equal in both shapes.

In [18]:
# Returns Copy or View?

import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

print(arr.reshape(2, 4).base) # 2 rows,4col
# It returns original array means it is a view.

[1 2 3 4 5 6 7 8]


In [24]:
# Unknown Dimension
# If you don't know what dimension, Pass -1 as the value, and NumPy will calculate this number for you.

import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

newarr = arr.reshape(2, 4) # it is simply 2 rows 4 columns
print(newarr)
newarr = arr.reshape(2, 2,-1) # in this 2 rows 2 col does not cover all 8 elements so pass -1 to adjust it with 3D array
print(newarr) 

[[1 2 3 4]
 [5 6 7 8]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [25]:
# Flattening the arrays
'''
Flattening array means converting a multidimensional array into a 1D array.

We can use reshape(-1) to do this.
'''
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

newarr = arr.reshape(-1)

print(newarr)

[1 2 3 4 5 6]


In [26]:
# NumPy Array Iterating
# If we iterate on a 1-D array it will go through each element one by one.
import numpy as np

arr = np.array([1, 2, 3])

for x in arr:
  print(x)

1
2
3


In [28]:
# Iterating 2-D Arrays
# In a 2-D array it will go through all the rows.
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

for x in arr:
  print(x) 

[1 2 3]
[4 5 6]


In [29]:
# Iterate on each scalar element of the 2-D array:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

for x in arr:
  for y in x:
    print(y) 

1
2
3
4
5
6


In [30]:
'''
Iterating 3-D Arrays

In a 3-D array it will go through all the 2-D arrays.
'''
import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

for x in arr:
  print(x) 

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]


In [31]:
# To return the actual values, the scalars, we have to iterate the arrays in each dimension.
import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

for x in arr:
  for y in x:
    for z in y:
      print(z) 

1
2
3
4
5
6
7
8
9
10
11
12


In [38]:
# Iterating Arrays Using nditer()

'''
In basic for loops, iterating through each scalar of an array we need to use n for loops which can be difficult to write for arrays with very high dimensionality.

The function nditer() is a helping function that can be used from very basic to very advanced iterations. It solves some basic issues which we face in iteration, lets go through it with examples.

'''
import numpy as np

arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
for x in np.nditer(arr):
    print(x)

1
2
3
4
5
6
7
8


In [50]:
#  Enumerated Iteration Using ndenumerate()
import numpy as np

arr = np.array([1, 2, 3])
for index,i in np.ndenumerate(arr):
    print(index,i) # prints with index no
for i in range(len(arr)):
    print(i,"=",arr[i])#same

(0,) 1
(1,) 2
(2,) 3
0 = 1
1 = 2
2 = 3


In [51]:
# np.ndenumerate() is like np.nditer(), very useful when accessing the elements of 1D,2D,3D arraysimport numpy as np. It also 
# print index numbers

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

for idx, x in np.ndenumerate(arr):
  print(idx, x) 

(0, 0) 1
(0, 1) 2
(0, 2) 3
(0, 3) 4
(1, 0) 5
(1, 1) 6
(1, 2) 7
(1, 3) 8


In [5]:
# New Chapter
# NumPy Joining Array

# In SQL we join tables based on a key, whereas in NumPy we join arrays by axes.
# We pass a sequence of arrays that we want to join to the concatenate() function, along with the axis. If axis is not explicitly passed, it is taken as 0.

# Join two arrays
import numpy as np

arr1 = np.array([[1,2,3],[4,5,6]])
arr2 = np.array([[7,8,9],[10,11,12]])
arr3 = np.concatenate((arr1,arr2))
print(arr3)
# Note for using concatenate(), both arrays must be of same dimension


[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [7]:
# Joining Arrays Using Stack Functions
# Stacking is same as concatenation, the only difference is that stacking is done along a new axis.
# We can concatenate two 1-D arrays along the second axis which would result in putting them one over the other, ie. stacking.
# We pass a sequence of arrays that we want to join to the stack() method along with the axis. If axis is not explicitly passed it is taken as 0.

import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])
arr3 = np.stack((arr1,arr2),axis=1)
print(arr3)

[[1 4]
 [2 5]
 [3 6]]


In [9]:
# 2D 
import numpy as np

arr1 = np.array([[1, 2], [3, 4]])

arr2 = np.array([[5, 6], [7, 8]])
arr3 = np.stack((arr1,arr2),axis=1)
print(arr3)

[[[1 2]
  [5 6]]

 [[3 4]
  [7 8]]]


In [10]:
# Stacking Along Rows
# NumPy provides a helper function: hstack() to stack along rows.

# 1D Array
import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])
arr3 = np.hstack((arr1,arr2))
print(arr3)

[1 2 3 4 5 6]


In [11]:
# 2D Array
import numpy as np

arr1 = np.array([[1, 2],[3,4]])

arr2 = np.array([[4, 5],[6,7]])
arr3 = np.hstack((arr1,arr2))
print(arr3)

[[1 2 4 5]
 [3 4 6 7]]


In [4]:
# New Chapter

# NumPy Splitting Array

# Splitting is reverse operation of Joining.
# Joining merges multiple arrays into one and Splitting breaks one array into multiple.
# We use array_split() for splitting arrays, we pass it the array we want to split and the number of splits.

import numpy as np
arr = np.array([1,2,3,4,5,6])
arr2 = np.array_split(arr,3)
print(arr2)
print(arr2[0])
for i in arr2:
    for j in i:
        print(j)



[array([1, 2]), array([3, 4]), array([5, 6])]
[1 2]
1
2
3
4
5
6


In [5]:
# If the array has less elements than required, it will adjust from the end accordingly.
import numpy as np
arr = np.array([1,2,3,4,5])
arr2 = np.array_split(arr,3)
print(arr2)



[array([1, 2]), array([3, 4]), array([5])]


In [ ]:
'''
Note: We also have the method split() available but it will not adjust the elements when elements are less in source array for splitting like in example above, array_split() worked properly but split() would fail.
'''

In [18]:
# Splitting 2-D Arrays
import numpy as np
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr2 = np.array_split(arr,3)
# print(arr2)
# print(arr2[0])
# for i in arr2:
#     for j in i:
#         for k in j:
#             print(k)
for i in np.ndenumerate(arr2):
    print(i)
for i in np.nditer(arr2):
    print(i)    

((0, 0, 0), 1)
((0, 0, 1), 2)
((0, 0, 2), 3)
((1, 0, 0), 4)
((1, 0, 1), 5)
((1, 0, 2), 6)
((2, 0, 0), 7)
((2, 0, 1), 8)
((2, 0, 2), 9)
(array(1), array(4), array(7))
(array(2), array(5), array(8))
(array(3), array(6), array(9))


In [33]:
# New Chapter

# NumPy Searching Arrays
# Searching Arrays
# where() method.

import numpy as np
arr = np.array([1,2,3,4,2,3,4,1,4,5])
arr2 = np.where(arr == 4)
print(arr)
print(arr2)
# It returns the indexes of value

[1 2 3 4 2 3 4 1 4 5]
(array([3, 6, 8], dtype=int64),)


In [34]:
# Find the indexes where the values are even:
import numpy as np
arr = np.array([1,2,3,4,5,6])
arr2 = np.where(arr%2==0)
print(arr2)


(array([1, 3, 5], dtype=int64),)


In [44]:
# Search Sorted
# There is a method called searchsorted() which performs a binary search in the array, and returns the index where the specified value would be inserted to maintain the search order.

# Find the indexes where the value 7 should be inserted:
import numpy as np
arr = np.array([1,2,4,5,6])
arr2 = np.searchsorted(arr,3)
print(arr2) # 2 index

2


In [45]:
# Multiple Values
import numpy as np

arr = np.array([1, 3, 5, 7])

x = np.searchsorted(arr, [2, 4, 6])

print(x)

[1 2 3]


In [47]:
# New Chapter
# NumPy Sorting Arrays

# sort()
# Note: This method returns a copy of the array, leaving the original array unchanged.

import numpy as np

arr = np.array([3, 2, 0, 1])
arr2 = np.sort(arr)
print(arr)
print(arr2)

[3 2 0 1]
[0 1 2 3]


In [48]:
# You can also sort arrays of strings, or any other data type:
import numpy as np

arr = np.array(['banana', 'cherry', 'apple'])

print(np.sort(arr))

['apple' 'banana' 'cherry']


In [49]:
# Sort a boolean array:

import numpy as np

arr = np.array([True, False, True])

print(np.sort(arr)) 

[False  True  True]


In [50]:
# Sorting a 2-D Array
# If you use the sort() method on a 2-D array, both arrays will be sorted:
import numpy as np

arr = np.array([[3, 2, 4], [5, 0, 1]])

print(np.sort(arr))

[[2 3 4]
 [0 1 5]]


In [53]:
# NumPy Filter Array
# In NumPy, you filter an array using a boolean index list.
# If the value at an index is True that element is contained in the filtered array, if the value at that index is False that element is excluded from the filtered array.

# Hard coded filter
import numpy as np
arr = np.array([1,2,3,10,11,12])
filterArray = [True,False,True,False,True,False]
newArray = arr[filterArray]
print(newArray)


[ 1  3 11]


In [57]:
# Print only those numbers which are greater than 10
import numpy as np
arr = np.array([1,2,3,10,11,12])
filterArray = []
for i in arr:
    if i>10:
        filterArray.append(True)
    else:        
        filterArray.append(False)
arr2 = arr[filterArray]
print(arr2)

[11 12]


In [59]:
# Creating Filter Directly From Array
# Direct method without using append and empty array

import numpy as np
arr = np.array([1,2,3,10,11,12])
filterArray = arr>10
print(filterArray) # [False False False False  True  True]
arr2 = arr[filterArray]
print(arr2)

[False False False False  True  True]
[11 12]
